twig:
    file_name_pattern: '*.twig'
    
    globals:
        # Reference the parameter from services.yaml
        uploads_events: '%uploads_events%'

when@test:
    twig:
        strict_variables: true